# Generated by Django 5.2.5 on 2025-09-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='include_packing',
            field=models.BooleanField(default=False, help_text='Include professional packing service for this Mini Move tier'),
        ),
        migrations.AddField(
            model_name='booking',
            name='include_unpacking',
            field=models.BooleanField(default=False, help_text='Include professional unpacking service for this Mini Move tier'),
        ),
        migrations.AddField(
            model_name='booking',
            name='organizing_total_cents',
            field=models.PositiveBigIntegerField(default=0, help_text='Total cost for packing and unpacking services'),
        ),
    ]
