# Generated by Django 5.2.5 on 2025-08-24 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='base_price_cents',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='coi_fee_cents',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_same_day_delivery',
            field=models.BooleanField(default=False, help_text='Same-day delivery (flat $360 rate)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='mini_move_package',
            field=models.ForeignKey(blank=True, help_text='Selected mini move package (Petite/Standard/Full)', null=True, on_delete=django.db.models.deletion.PROTECT, to='services.minimovepackage'),
        ),
        migrations.AddField(
            model_name='booking',
            name='specialty_items',
            field=models.ManyToManyField(blank=True, help_text='Selected specialty items (Peloton, Surfboard, etc.)', to='services.specialtyitem'),
        ),
        migrations.AddField(
            model_name='booking',
            name='standard_delivery_item_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of items for standard delivery', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='surcharge_cents',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
