# Generated by Django 5.2.5 on 2025-09-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_include_packing_booking_include_unpacking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='geographic_surcharge_cents',
            field=models.PositiveBigIntegerField(default=0, help_text='$175 surcharge for 30+ miles from Manhattan'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_outside_core_area',
            field=models.BooleanField(default=False, help_text='True if pickup/delivery is 30+ miles from Manhattan'),
        ),
        migrations.AddField(
            model_name='booking',
            name='organizing_tax_cents',
            field=models.PositiveBigIntegerField(default=0, help_text='Tax on organizing services'),
        ),
        migrations.AddField(
            model_name='booking',
            name='specific_pickup_hour',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(8, '8:00 AM - 9:00 AM'), (9, '9:00 AM - 10:00 AM'), (10, '10:00 AM - 11:00 AM')], help_text='Specific hour for 1-hour window pickup', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_window_surcharge_cents',
            field=models.PositiveBigIntegerField(default=0, help_text='Surcharge for specific 1-hour window'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_time',
            field=models.CharField(choices=[('morning', '8 AM - 11 AM'), ('morning_specific', 'Specific 1-hour window (surcharge applies)'), ('no_time_preference', 'No time preference (available for certain packages)')], default='morning', max_length=30),
        ),
    ]
