# Generated by Django 5.2.5 on 2025-10-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_geographic_surcharge_cents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='blade_airport',
            field=models.CharField(blank=True, choices=[('JFK', 'JFK International Airport'), ('EWR', 'Newark Liberty International Airport')], help_text='Destination airport for BLADE transfer', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='blade_bag_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of bags for BLADE transfer (minimum 2)', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='blade_flight_date',
            field=models.DateField(blank=True, help_text='Date of BLADE flight', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='blade_flight_time',
            field=models.TimeField(blank=True, help_text='Time of BLADE flight departure', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='blade_ready_time',
            field=models.TimeField(blank=True, help_text='Auto-calculated: when bags must be ready for pickup', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('mini_move', 'Mini Move'), ('standard_delivery', 'Standard Delivery'), ('specialty_item', 'Specialty Item'), ('blade_transfer', 'BLADE Airport Transfer')], max_length=20),
        ),
    ]
