# Generated by Django 5.2.5 on 2025-10-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_blade_airport_booking_blade_bag_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='same_day_surcharge_cents',
            field=models.PositiveBigIntegerField(default=0, help_text='Same-day delivery surcharge ($360)'),
        ),
    ]
