# Generated by Django 5.2.5 on 2025-10-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_same_day_surcharge_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When 24hr reminder email was sent', null=True),
        ),
    ]
