# Generated by Django 5.2.5 on 2025-10-20 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_add_specialty_item_quantities'),
        ('services', '0007_remove_specialty_item_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['customer'], name='bookings_ad_custome_ebf57e_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['zip_code'], name='bookings_ad_zip_cod_e9e007_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_number'], name='bookings_booking_number_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['pickup_date', 'status'], name='bookings_pickup_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'created_at'], name='bookings_customer_created_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'pickup_date'], name='bookings_status_pickup_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='bookings_created_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service_type'], name='bookings_service_type_idx'),
        ),
        migrations.AddIndex(
            model_name='guestcheckout',
            index=models.Index(fields=['email'], name='bookings_gu_email_c611ad_idx'),
        ),
    ]
