# Generated by Django 5.2.5 on 2026-02-07 18:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_address_bookings_ad_custome_ebf57e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10)),
                ('discount_value', models.PositiveIntegerField(help_text='Percentage (e.g. 20 for 20%) or fixed amount in cents (e.g. 5000 for $50)')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum total uses. Null = unlimited.', null=True)),
                ('max_uses_per_customer', models.PositiveIntegerField(default=1, help_text='Maximum uses per customer/email address')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Expiration date. Null = never expires.', null=True)),
                ('minimum_order_cents', models.PositiveIntegerField(default=0, help_text='Minimum order total (pre-discount) in cents')),
                ('maximum_discount_cents', models.PositiveIntegerField(blank=True, help_text='Cap the discount amount (for percentage codes). Null = no cap.', null=True)),
                ('allowed_service_types', models.JSONField(blank=True, default=list, help_text='Service types this code applies to. Empty = all services.')),
                ('is_active', models.BooleanField(default=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings_discount_code',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount_cents',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='pre_discount_total_cents',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('mini_move', 'Mini Move'), ('standard_delivery', 'Standard Delivery'), ('specialty_item', 'Specialty Item'), ('blade_transfer', 'Airport Transfer')], max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.discountcode'),
        ),
        migrations.CreateModel(
            name='DiscountCodeUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_email', models.EmailField(max_length=254)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking')),
                ('discount_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='bookings.discountcode')),
            ],
            options={
                'db_table': 'bookings_discount_code_usage',
                'indexes': [models.Index(fields=['discount_code', 'customer_email'], name='discount_usage_customer_idx')],
            },
        ),
    ]
