# Generated by Django 5.2.5 on 2026-02-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_discountcode_booking_discount_amount_cents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='blade_terminal',
            field=models.CharField(blank=True, help_text='Airport terminal (JFK: 1/4/5/7/8, EWR: A/B/C)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='transfer_direction',
            field=models.CharField(choices=[('to_airport', 'To Airport'), ('from_airport', 'From Airport')], default='to_airport', help_text='Transfer direction: to airport or from airport', max_length=15),
        ),
    ]
