# Generated by Django 5.2.5 on 2026-02-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_add_bidirectional_airport_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='item_description',
            field=models.TextField(blank=True, help_text='Customer description of items for standard delivery', null=True),
        ),
    ]
