# Generated by Django 5.2.5 on 2026-04-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_staff_booking_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='max_uses_per_customer',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Maximum uses per customer/email address. Leave blank for unlimited.', null=True),
        ),
    ]
