# Generated by Django 5.2.5 on 2025-09-13 23:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_include_packing_booking_include_unpacking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnfleetTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('onfleet_task_id', models.CharField(max_length=100, unique=True)),
                ('onfleet_short_id', models.CharField(blank=True, max_length=20)),
                ('tracking_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onfleet_task', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Onfleet Task',
                'verbose_name_plural': 'Onfleet Tasks',
                'db_table': 'logistics_onfleet_task',
                'indexes': [models.Index(fields=['onfleet_task_id'], name='logistics_o_onfleet_7020df_idx'), models.Index(fields=['status'], name='logistics_o_status_f0c32e_idx')],
            },
        ),
    ]
