# Generated by Django 5.2.5 on 2025-10-12 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_same_day_surcharge_cents'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onfleettask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Onfleet Task', 'verbose_name_plural': 'Onfleet Tasks'},
        ),
        migrations.RemoveIndex(
            model_name='onfleettask',
            name='logistics_o_status_f0c32e_idx',
        ),
        migrations.AddField(
            model_name='onfleettask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onfleettask',
            name='delivery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onfleettask',
            name='environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20),
        ),
        migrations.AddField(
            model_name='onfleettask',
            name='estimated_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onfleettask',
            name='failure_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onfleettask',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='onfleettask',
            name='linked_task',
            field=models.ForeignKey(blank=True, help_text='For dropoff tasks, links to the pickup task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_tasks', to='logistics.onfleettask'),
        ),
        migrations.AddField(
            model_name='onfleettask',
            name='photo_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='onfleettask',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='onfleettask',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='onfleettask',
            name='signature_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='onfleettask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onfleettask',
            name='task_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff')], default='dropoff', help_text='Pickup or Dropoff task', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onfleettask',
            name='worker_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='onfleettask',
            name='worker_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='onfleettask',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onfleet_tasks', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='onfleettask',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned to Driver'), ('active', 'Driver En Route'), ('completed', 'Completed'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='onfleettask',
            name='tracking_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='onfleettask',
            index=models.Index(fields=['booking', 'task_type'], name='logistics_o_booking_981805_idx'),
        ),
        migrations.AddIndex(
            model_name='onfleettask',
            index=models.Index(fields=['status', 'environment'], name='logistics_o_status_5ed770_idx'),
        ),
        migrations.AddIndex(
            model_name='onfleettask',
            index=models.Index(fields=['created_at'], name='logistics_o_created_6f3156_idx'),
        ),
        migrations.AddConstraint(
            model_name='onfleettask',
            constraint=models.UniqueConstraint(fields=('booking', 'task_type'), name='unique_task_type_per_booking'),
        ),
    ]
