# Generated by Django 5.2.5 on 2025-09-08 21:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizingService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('petite_packing', 'Petite Packing'), ('standard_packing', 'Standard Packing'), ('full_packing', 'Full Packing'), ('petite_unpacking', 'Petite Unpacking'), ('standard_unpacking', 'Standard Unpacking'), ('full_unpacking', 'Full Unpacking')], max_length=30, unique=True)),
                ('mini_move_tier', models.CharField(choices=[('petite', 'Petite'), ('standard', 'Standard'), ('full', 'Full')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_cents', models.PositiveBigIntegerField()),
                ('duration_hours', models.PositiveIntegerField()),
                ('organizer_count', models.PositiveIntegerField()),
                ('supplies_allowance_cents', models.PositiveBigIntegerField(default=0, help_text='Supplies allowance in cents (packing services only)')),
                ('is_packing_service', models.BooleanField(help_text='True for packing services (with supplies), False for unpacking (organizing only)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'services_organizing_service',
                'ordering': ['mini_move_tier', 'is_packing_service', 'price_cents'],
            },
        ),
    ]
