# Generated by Django 5.2.5 on 2025-09-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_populate_organizing_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='surchargerule',
            name='applies_to_service_type',
            field=models.CharField(choices=[('all', 'All Services'), ('mini_move', 'Mini Moves Only'), ('standard_delivery', 'Standard Delivery Only'), ('specialty_item', 'Specialty Items Only')], default='all', help_text='Which service types this surcharge applies to', max_length=20),
        ),
    ]
