# Generated by Django 5.2.5 on 2025-09-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_surchargerule_applies_to_service_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VanSchedule',
        ),
    ]
