# Generated by Django 5.2.5 on 2025-10-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_van_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialtyitem',
            name='requires_van_schedule',
        ),
    ]
