# Generated by Django 5.2.5 on 2025-10-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_specialtyitem_requires_van_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialtyitem',
            name='item_type',
            field=models.CharField(help_text="Unique identifier for this specialty item (e.g., 'bicycle', 'kayak')", max_length=30, unique=True),
        ),
    ]
