# Generated by Django 5.2.5 on 2026-01-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_specialty_item_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='surchargerule',
            name='end_date',
            field=models.DateField(blank=True, help_text='End of date range (inclusive)', null=True),
        ),
        migrations.AddField(
            model_name='surchargerule',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start of date range (inclusive)', null=True),
        ),
        migrations.AlterField(
            model_name='surchargerule',
            name='specific_date',
            field=models.DateField(blank=True, help_text='Single specific date (use this OR start/end date range)', null=True),
        ),
    ]
