# Generated by Django 5.2.5 on 2025-09-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='preferred_pickup_time',
            field=models.CharField(choices=[('morning', '8 AM - 11 AM'), ('morning_specific', 'Specific 1-hour window'), ('no_time_preference', 'No time preference')], default='morning', max_length=30),
        ),
    ]
