# Generated by Django 5.2.5 on 2025-10-20 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_emailverificationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customerpaymentmethod',
            index=models.Index(fields=['user', 'is_active'], name='payment_method_user_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpaymentmethod',
            index=models.Index(fields=['stripe_payment_method_id'], name='payment_method_stripe_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['user'], name='customer_profile_user_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['stripe_customer_id'], name='customer_stripe_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['is_vip'], name='customer_vip_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['token'], name='email_verify_token_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['verified', 'expires_at'], name='email_verify_status_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['token'], name='password_reset_token_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', 'used'], name='password_reset_user_idx'),
        ),
        migrations.AddIndex(
            model_name='savedaddress',
            index=models.Index(fields=['user', 'is_active'], name='saved_addr_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='savedaddress',
            index=models.Index(fields=['times_used'], name='saved_addr_usage_idx'),
        ),
        migrations.AddIndex(
            model_name='savedaddress',
            index=models.Index(fields=['user', 'last_used_at'], name='saved_addr_recent_idx'),
        ),
    ]
