# Generated by Django 5.2.5 on 2026-02-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_payments_stripe_intent_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
