# Generated by Django 5.2.5 on 2026-03-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_partially_refunded_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_checkout_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
