# Generated by Django 5.2.5 on 2026-06-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_make_booking_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaudit',
            name='action',
            field=models.CharField(choices=[('payment_created', 'Payment Created'), ('payment_succeeded', 'Payment Succeeded'), ('payment_failed', 'Payment Failed'), ('refund_requested', 'Refund Requested'), ('refund_approved', 'Refund Approved'), ('refund_completed', 'Refund Completed'), ('orphan_alert_sent', 'Orphan Alert Sent'), ('booking_auto_recovered', 'Booking Auto-Recovered'), ('duplicate_charge_detected', 'Duplicate Charge Detected'), ('auto_recovery_failed', 'Auto-Recovery Failed')], max_length=30),
        ),
    ]
